### PR TITLE
Make Freezer extendable (closes #22)

### LINKED ISSUE #22: Extending Freezer
Good day, @arqex ! Thank you for your work!

I want to inherit `Freezer` in my class (in ECMAScript 6). What do you think about possibility of it?

But `Freezer.prototype` doesn't have any methods such as `get` and `set`. Can this be changed?

### PR DESCRIPTION
**Pull request by kuraga**

### CODE REVIEW

**Comment by arqex** [comment]
Hi @kuraga 

I have been playing a bit to see what's the better way of making freezer extendable and it was way easier than what we thought! The key part was the commit you made with

`Freezer.prototype.constructor = Freezer;`

Just only with that line, Freezer becomes extendable. All the rest is not needed. See

http://bit.ly/1Et6L14

**Comment by kuraga** [comment]
@arqex yes, but `get` and `set` methods are unavailable.

**Comment by marquex** [comment]
I didn't try with Freezer itself, but if the method `sayHi` works in the example, `get` and `set` should work in freezer. Don't they?

**Comment by kuraga** [comment]
No. All these methods (and `constructor`, too) come from superclass' `prototype`, i.e. `Freezer.prototype`.

In current (`master` branch I meen) implementation `Freezer.prototype` doesn't have neither `constructor`, nor `get`, nor `set`.

You propose set `Freezer.prototype` only. Yes, we can extend but other methods are unavailable.

My patch moves all needed methods (`constructor`, `get`, `set`) to `Freezer.prototype`. And everything works.

**Comment by kuraga** [comment]
Hm. stop. One more moment

**Comment by kuraga** [comment]
Hell, you're completely right...

**Comment by kuraga** [comment]
See #26

**Pull request closed without merging**
